### PR TITLE
Add Japanese Language

### PR DESCRIPTION
**Pull request by sarisarinyama**
Added Japanese language file. The translation quality is a modification based on the google translation. 
The quality is not high. 

sorry
This version is buggy

### CODE REVIEW

**Comment by Wano-k** [comment]
Thank you very much, checking this and will probably add it to the engine and put a warning on low quality translation. I will also add a warning in steam description to ask some help to Japanese speakers to review it!

**Comment by sarisarinyama** [comment]
Thank you as well!
It's my first time to do this, so it was a poor result, but I learned a lot.

P.S?
I think the bronze helmet type of the armor in the sample data is
incorrectly turned into a sword.

**Comment by Wano-k** [comment]
Thanks for the bronze helmet, correcting this! Tell when you think you're done with it. I will merge it a few days before next update (that will only come in a few weeks since I'm currently not coding!)

**Comment by sarisarinyama** [comment]
> Thanks for the bronze helmet, correcting this! Tell when you think you're done with it. I will merge it a few days before next update (that will only come in a few weeks since I'm currently not coding!)

I tried it for a few hours. 
There doesn't seem to be any problems at this time, 
so please merge.

**Pull request merged**
